apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dify-common-secret
  namespace: dify
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: dify-common-secret
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        # DB Keys (Required for CNPG and Dify)
        username: "dify"
        password: "{{ .db_pass }}"
        DB_PASSWORD: "{{ .db_pass }}"
        # Redis
        REDIS_PASSWORD: "{{ .redis_pass }}"
        # MinIO
        MINIO_ROOT_USER: "{{ .minio_user }}"
        MINIO_ROOT_PASSWORD: "{{ .minio_pass }}"
        # Dify Core
        SECRET_KEY: "{{ .dify_secret_key }}"
  data:
    - secretKey: db_pass
      remoteRef:
        key: dify/db
        property: password
    - secretKey: redis_pass
      remoteRef:
        key: dify/redis
        property: password
    - secretKey: minio_user
      remoteRef:
        key: dify/minio
        property: username
    - secretKey: minio_pass
      remoteRef:
        key: dify/minio
        property: password
    - secretKey: dify_secret_key
      remoteRef:
        key: dify/core
        property: secret_key
