apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: backend
          image: viet2212/pythonbacken:main-10-2a18f44
          env:
            - name: DB_HOST
              value: "python-db-rw.backend.svc.cluster.local"
            - name: DB_NAME
              value: "app_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: python-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: python-db-secret
                  key: password
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
