apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: python-db-ext-secret
  namespace: backend
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-store # POINTS TO THE GLOBAL STORE
    kind: ClusterSecretStore  # CHANGED FROM SecretStore
  target:
    name: python-db-secret
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: backenddb
        property: username
    - secretKey: password
      remoteRef:
        key: backenddb
        property: password
